package cs2340.todo_team_name.spacetrader.enums;

public enum ResourceType {
    NOSPECIALRESOURCES, MINERALRICH, DESERT, LOTSOFWATER, RICHSOIL, POORSOIL, RICHFUANA,
    LIFELESS, WEIRDMUSHROOMS, LOTSOFHERBS, ARTISTIC, WARLIKE

}
